ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "alertWebhookUrl" TEXT;
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "alertThreshold" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Device" ADD COLUMN IF NOT EXISTS "lastAlertAt" TIMESTAMP(3);
